### ISSUE TITLE
Add `/kill` command

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/TeX-Bot-Py-V2#105]
This is useful for committee members that do not have SSH access to the server the bot runs on, when the bot needs to be emergency shut down. A 2 stage confirmation message should be sent so that the committee member understands what the successful completion of this command will do, and make sure they actually meant to do that.

Edit:
By "2 stage confirmation message" I mean just an extra button confirmation, on top of using the command itself. (Similar to how the `/strike` command asks for confirmation to execute an action.

**Comment by FrozenDude101** [comment]
When does the bot ever need a multi-stage shutdown message?
A) In general if a person is on committee their actions should be trusted as an elected position.
B) When could this be performed before a "bad thing" was executed? Some commands have intermediate steps, but not all.
    Should all bot commands require a secondary?

**Comment by LMBishop** [comment]
![image](https://github.com/CSSUoB/TeX-Bot-Py-V2/assets/13875753/49602d0b-37d6-41dd-91d1-4bf7f94d3ed5)

Just sayin

**Comment by CarrotManMatt** [comment]
> In general if a person is on committee their actions should be trusted as an elected position.

Agreed, it's not meant to limit the powers of committee because of some untrustworthiness. The purpose of the confirmation is similar to the confirmation for the `/strike` command, or when a program asks if you are sure you want to close it because you have unsaved changes. It's an irreversible action that should not be executed on accident, because of a miss-click/tab-completion error, for example.


> When could this be performed before a "bad thing" was executed?

It wouldn't be able to prevent a command from running, would more act as a cleanup operation after an emergency event occurs so that nothing worse happens.


> Some commands have intermediate steps, but not all. Should all bot commands require a secondary?

I am unsure how this relates to this issue. All other commands will be left as they are because a confirmation request would be unnecessary.

**Comment by CarrotManMatt** [comment]
@LMBishop, Kicking the bot is a nice idea, but does not stop it from running. Many of the commands can be run from a DM between a user and the bot and kicking would not prevent this.

Admittedly an extra event listener could be made to kill the bot if it is ever kicked from the [main guild](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/improve-variable-names-and-install-docs-and-.gitignore/README.md#guild--server), but that seems like an extra unnecessary step rather than a simple `/kill` command.

**Comment by CarrotManMatt** [comment]
In theory there aren't any currently. I think it would just be more advantageous to have the command available at a time of crisis, where there are no committee members with ssh access available, than not have it.

**Comment by codemicro** [comment]
I don't see why this warrants *not* implementing - it's simple and a good backup plan. Who knows what we could end up implementing in the future that might warrant this.
