### ISSUE TITLE
Bot potentially thrashing Discord API

### ISSUE THREAD

**Issue by codemicro** [CSSUoB/TeX-Bot-Py-V2#114]
Discord shutdown the bot earlier this morning with the following message.

![Screenshot_20231212_094359_Discord.jpg](https://github.com/CSSUoB/TeX-Bot-Py-V2/assets/25284325/b8d98d50-30e4-4c03-b821-2c49ca7bc15e)

As there has been other usage of the token elsewhere in the past 24 hours, this may not be directly related to the bot, but may warrant investigation.

**Comment by Thatsmusic99** [comment]
hi yes bot is online again it was probably because docker kept rebooting it after it kept crashing from the PR incident yesterday

**Comment by CarrotManMatt** [comment]
The docker container's restart policy was the issue causing this in CSS's deplyment. It is now being looked into. There seems to be no issues from the Discord connection side.
