### ISSUE TITLE
Move invite URL generation to `on_ready` event

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/TeX-Bot-Py-V2#166]
Rather than generating the invite URL from a util CLI command, it should just be output when the bot is run.

If the selected guild (from the given ID) is not available to the bot, the bot should shut down. An error message should be alerted that the bot needs to be invited using the outputted invite URL link.

Completion of this issue should also include removing the whole of the CLI util command framework.

**Comment by edwinchan129** [comment]
I'd like to take this issue on. Is there any helpful files/lines of code I should start looking at for this issue?

**Comment by CarrotManMatt** [comment]
Hi @edwinchan129! We really appreciate you looking to contribute to TeX-Bot. The main changes for this issue would be to:
* Move [the `InviteURLGenerator.run()` function](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/utils/generate_invite_url.py#L61) from that class into its own global-scope function within [`utils/generate_invite_url.py`](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/utils/generate_invite_url.py#L61)
* Remove [the function `main()` from `utils/__init__.py`](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/utils/__init__.py#L36)
* Delete [`utils/__main__.py`](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/utils/__main__.py)
* Delete [`utils/base_utility_function.py`](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/utils/base_utility_function.py)
* Call [your newly created `generate_invite_url()` function](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/utils/generate_invite_url.py#L62) within the [`on_ready()` function within `cogs/startup.py`](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/cogs/startup.py#L32)

**Comment by edwinchan129** [comment]
Do you mean that the bot should output a link when this command "poetry run python -m main" is run instead and generate an invite link based on variables set on the .env file? I'm also unsure on how to get Tex-Bot to run properly in my test server as I'm unsure what to put into the required variables: MEMBERS_LIST_URL, MEMBERS_LIST_URL_SESSION_COOKIE, and MODERATION_DOCUMENT_URL.

**Comment by CarrotManMatt** [comment]
>  Do you mean that the bot should output a link when this command "poetry run python -m main" is run instead

In a sense. If you call the `logger.info()` function from within [the `on_ready()` function within `cogs/startup.py`](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/5d3b14b66468f6a70d3b0a935ef3b14db3777a47/cogs/startup.py#L32) it will output the generated link when the bot starts up (either automatically or by running the command you mentioned.

> generate an invite link based on variables set on the .env file?

Retrieving the main guild is already done within the `on_ready()` function. So it *technically* uses the values from the `.env` file, however you won't need to worry about that. I'd recommend taking a look at the existing code within the `on_ready()` function to see how the [`main_guild` object](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/a334998480df8dee7f4bb4811a35183eb580ce53/cogs/startup.py#L63C13-L63C23) is used.

> I'm unsure what to put into the required variables: MEMBERS_LIST_URL, MEMBERS_LIST_URL_SESSION_COOKIE, and MODERATION_DOCUMENT_URL

Apologies about this. The current state of the project makes these variables required, however they should be optional when running locally. They are used only for the `/makemember` function so if you're not testing that they should be optional (unfortunately they're not).

* For `MEMBERS_LIST_URL` you can just put any valid URL that you like
* For `MEMBERS_LIST_URL_SESSION_COOKIE` you can put any sequence of 128 letters (just has to match this regex: `\A[A-Fa-f\d]{128,256}\Z`)
* For `MODERATION_DOCUMENT_URL` you can just put any valid URL that you like

See the `.env.example` file for descriptions on all these environment variables & the docs [here](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/main/README.md#setting-environment-variables)

**Comment by edwinchan129** [comment]
Alright I got the basics of it down and it seems to be working at generating an invite url. I just want to ask some more clarifying questions before I test it further and the submit a pull request.

>If the selected guild (from the given ID) is not available to the bot, the bot should shut down. An error message should be alerted that the bot needs to be invited using the outputted invite URL link.

Does this mean that the the invite url should be generated each time the bot is run, but the bot should exit out if the user doesn't invite the bot to the guild specified in the .env file? I see in the startup.py that there is a check for whether the bot has a main_guild set, but this itself doesn't verify whether the bot is already in the server before proceeding. It does, however, shut down if the main_guild isn't set. Should this be modified to the case I mentioned or is simply generating a valid invite url at the moment all that matters?

**Comment by CarrotManMatt** [comment]
Good thoughts!

I would suggest that if the bot is already in the selected guild, then the invite URL should only be outputted if the log level is set to `DEBUG`, otherwise it continues running but does not output the invite URL.

If the bot is not yet in the selected guild (hence main_guild does not get set because the guild is not within the list of guild that the bot is within) it should always output the invite URL and then shut down.
