### ISSUE TITLE
Sending reminders to users does not check whether they are within the server

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/TeX-Bot-Py-V2#181]
An additional check is required before sending a user a reminder message to ensure they are still within the server. This is due to there possibly being a delay between the user being logged & the user needing the reminder sent. (So the check is not necessary for every place the bot ever sends a message to a user, just for reminder tasks.)

A log message should be sent if the bot finds a user that needs reminding but no longer is in the server. However, this log should be at level `info` to prevent spamming the log channels.

**Comment by MattyTheHacker** [comment]
![image](https://github.com/CSSUoB/TeX-Bot-Py-V2/assets/18513864/9c6d971e-e21e-4a9a-a178-5863022ceedb)

**Comment by MattyTheHacker** [comment]
Should be noted I don't know if it's 100% the fact they weren't in the server anymore - just a random guess

**Comment by CarrotManMatt** [comment]
It'll be a good check to make nonetheless and if the issue persists moree debugging can be done from that point forwards👍🏻
