### ISSUE TITLE
Unknown interaction error when inducting users

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#208]
![image](https://github.com/CSSUoB/TeX-Bot-Py-V2/assets/18513864/a6638e34-2a92-413a-8f60-4f7d6ee4430f)

seems to happen at random when inducting

**Comment by CarrotManMatt** [comment]
This may be due to the total response time taking >3 seconds. Therefore a deferral may be required. It is imperative that testing is done to see whether the response time is too long and that is the issue. Deferral is a last resort solution.

**Comment by MattyTheHacker** [comment]
Yeah the induction command has started not responding in time quite often so I'm fairly confident it's that.
