### ISSUE TITLE
TeX-Bot did not shutdown correctly

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#260]
![image](https://github.com/user-attachments/assets/8184be68-45bf-4535-a109-0b5c574bc10f)
![image](https://github.com/user-attachments/assets/696ff5d6-22b6-4b02-abf5-acf9b9eccdd6)

**Comment by CarrotManMatt** [comment]
Do you have the logs further up, as this stacktrace doesn't include the actual error that caused the call to `TeXBot
close()`?

I'll need to perform more testing to ensure that once `TeXBot.close()` is called. The shutdown is always successful.

**Comment by MattyTheHacker** [comment]
> Do you have the logs further up, as this stacktrace doesn't include the actual error that caused the call to `TeXBot close()`?
> 
> I'll need to perform more testing to ensure that once `TeXBot.close()` is called. The shutdown is always successful.

There was nothing further up, just the usual database messages - the exit was initiated by me doing ctrl + c in the terminal

**Comment by CarrotManMatt** [comment]
Gotcha, that was just the info I needed👍🏻
