### ISSUE TITLE
Discord API Connection Error

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#270]
![image](https://github.com/user-attachments/assets/ee434aea-2886-4dad-8168-1ed6e0040987)

**Comment by CarrotManMatt** [comment]
I think this is likely a synchronisation error between TeX-Bot running & Discord. Restarting the application may fix it.

**Comment by CarrotManMatt** [comment]
Closed due to lack of further discussion.
