### ISSUE TITLE
Update build-push github action

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#274]
The current build and push action is on v5 but needs to be updated to v6. This seems to require adding additional details or possibly buildx setup steps.

See:
https://github.com/docker/build-push-action/issues/851
https://github.com/orgs/community/discussions/45969
https://github.com/blakeblackshear/frigate/issues/2982

**Comment by CarrotManMatt** [comment]
Seems like the issue was a temporary GitHub runner issue. If the action had been rerun the container image would have been installable
