### ISSUE TITLE
Current auto created bot role does not have access to committee channels by default

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#324]
CSS' setup is slightly fucked that we have given the bot a completely separate role to the default one it creates itself which has full admin permissions

**Comment by Thatsmusic99** [comment]
come again

**Comment by MattyTheHacker** [comment]
The bot creates it's own "TeX" role when it's invited to a server, intended to give it all the necessary permissions to Exist:tm: 

This default role it creates doesn't have access to committee channels.

In CSS TeX *does* have access to committee channels because we've(not me) seemingly given it a new role (created manually) which has the Administrator permission
