### ISSUE TITLE
Inducting users doesn't remove the Applicant role

### ISSUE THREAD

**Issue by codemicro** [CSSUoB/TeX-Bot-Py-V2#4]
In cases where people with the `Applicant` role are being inducted, this is not removed from them. I think this should probably be done so people don't forget to do it manually.

**Comment by codemicro** [comment]
test to see if i fixed the thing

**Comment by MattyTheHacker** [comment]
Similar: https://github.com/CSSUoB/TeX-Bot-JS/issues/30

Accidently put it on the wrong repo lmao

**Comment by MattyTheHacker** [comment]
Have thought about this a bit - I do think it'd be valuable to implement both, that way applicants can effectively induct themselves if they've already purchased membership

**Comment by MattyTheHacker** [comment]
hmm although it has also just occured to me this would apply to non-applicants too, in effect people could buy membership to bypass having to introduce, though I'm not confident that's actually a bad thing??? probably needs a good discussion
