### ISSUE TITLE
Add shield badges to README.md

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/TeX-Bot-Py-V2#78]
To improve communicating the good design of this repo, shield badge images should be added from https://shields.io. See [the mypy repository's README.md](https://github.com/python/mypy/blob/master/README.md?plain=1) for a good example.

**Comment by awsloth** [comment]
Happy to add Python version, Ruff, MyPy, Docs Passing and Py-Cord version. Would you want anything else

**Comment by CarrotManMatt** [comment]
> Happy to add Python version, Ruff, MyPy, Docs Passing and Py-Cord version. Would you want anything else

Maybe the current project version? (defined in [pyproject.toml](https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/main/pyproject.toml)), there was a project I saw that had one to emphasise that contributions are welcomed.

**Comment by awsloth** [comment]
Got a version here: https://github.com/awsloth/TeX-Bot-Py-V2/blob/78-shield-badges/README.md
Should I reorder the badges or change the colour of any?

**Comment by awsloth** [comment]
Oh yes I forgot to add the ruff badge. Should I make the python version static and we can then update it when python version goes up as this won't happen too often, or try to find a workaround to show the version in `pyproject.toml`.

**Comment by CarrotManMatt** [comment]
Static sounds best for the python version as we'll manually need to update things for the new version, and updating this icon can be part of that pull request. Hopefully everything will still be 3.11 compatible, so we can do one of the multipart shields with 3.11 & 3.12.
