### ISSUE TITLE
Add functionality to makemember command to handle applicants

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#9]
if a user with the applicant role successfully uses the /makemember command, give them the member role but also remove their applicant role

**Comment by MattyTheHacker** [comment]
Test

**Comment by CarrotManMatt** [comment]
As discussed by committee, any user that can successfully use the `/makemember` command (because they bought membership to CSS) should be automatically inducted.
